<?php
$helper = $this->getSearchHelper();
$dataHelper = $this->getModuleHelper();
$configModel = $this->getModuleConfig();

//init vars
$searchDelay = $configModel->getSearchDelay();

$ajaxUrl = $this->getAjaxSearchUrl();
?>
<script type="text/javascript">
    function AutoSearchCheckBrowser(e) {
        var key = '';
        if (window.event)
            key = window.event.keyCode;     //IE
        else
            key = e.which;     //firefox
        return key;
    }

    require([
        'jquery',
        'jquery/ui'
    ], function($){
        jQuery(document).ready(function($) {
            $(document).find('.auto-search-block').each(function(index, el) {
                var autoSearchBlock          = $(this);
                var autoSearchSelector = autoSearchBlock.find('input[name=\'<?php echo $helper->getQueryParamName() ?>\']').eq(0);
                var cache = suggested = [];

                if( typeof(autoSearchSelector.autocomplete) == 'function') {
                    autoSearchSelector.autocomplete({
                        delay: <?php echo (int)$searchDelay ?>,
                        minLength: 0,
                        appendTo: autoSearchBlock.find('.auto-search').eq(0),
                        position: {
                            my: "left top",
                            at: "left bottom",
                            collision: "none"
                        },
                        search: function(event, ui) {
                            $(this).addClass("ui-autocomplete-loading");
                        },
                        open: function() {
                            $(this).removeClass("ui-autocomplete-loading");
                        },
                        select: function(event, ui) {
                            var key = AutoSearchCheckBrowser(event);
                            if (key === 13) return true;
                            var autoSearchText = $.trim(autoSearchSelector.val());
                        },
                        source: function(request, response) {
                            var autoSearchText = encodeURIComponent(request.term);
                            var rData = 'q=' + autoSearchText;
                            $.ajax({
                                url: '<?php echo $ajaxUrl ?>',
                                dataType: 'json',
                                data: rData,
                                type:'POST',
                                beforeSend: function() {
                                    if(!$.trim(autoSearchSelector.val())){
                                        autoSearchSelector.removeClass("ui-autocomplete-loading");
                                        autoSearchBlock.find('.ui-autocomplete').eq(0).css({'display':'none'});
                                        return false;
                                    }
                                    if(typeof(cache[autoSearchText]) != 'undefined'){
                                        var items = cache[autoSearchText];
                                        //total = cache[autoSearchText].total;
                                        if(items.products && items.products.length > 0) {
                                            response($.map(items.products, function(item) {
                                                return {
                                                    html: item.html,
                                                    value: autoSearchText
                                                }
                                            }));

                                        }
                                        return false;
                                    }
                                },
                                success: function(data) {
                                    var text_view_all = '<?php echo __("View all %s items →");?>';
                                    var products = data.products;
                                    var total = data.total;
                                    var suggested = data.suggested;
                                    var suggestHtml = '';
                                    var length = suggested.length;
                                    for (var i = 0; i < length; i++) {
                                        suggestHtml += '<a href="' + suggested[i]['url'] + '">' + suggested[i]['query_text'] + '<span>(' + suggested[i]['num_results'] + ')</span>' + '</a>';
                                        if( i !== (length-1) )
                                            suggestHtml += ', ';
                                    }
                                    var rItem = [];
                                    if( length > 0 ){
                                        var defaultText = '<div class="suggested-default-hd"><?php echo __('Most relevant matches are shown. Click Search for more items') ?></div>';
                                        rItem['name'] = rItem['image'] = rItem['link'] = '';
                                        rItem['price'] = rItem['product_id'] = 0;
                                        rItem['html'] = defaultText + '<div class="suggested-keywords"><?php echo __('Suggested keywords: ') ?>' + suggestHtml + '</div>';
                                        products.unshift(rItem);
                                    }
                                    if( total ){
                                        text_view_all = text_view_all.replace(/%s/gi, total);
                                        rItem = [];
                                        rItem['name'] = rItem['image'] = rItem['link'] = '';
                                        rItem['price'] = rItem['product_id'] = 0;
                                        rItem['html'] = '<a class="smore" href="<?php echo $this->getCatalogSearchLink(); ?>?'+rData+'" onclick="window.location=this.href">'+text_view_all+'</a>';
                                        products.push(rItem);
                                    }
                                    cache[autoSearchText] = data;

                                    response($.map(products, function(item) {
                                        return {
                                            html: item.html,
                                            value: autoSearchText
                                        }
                                    }));
                                }
                            });
                        },
                        focus: function(event, ui) {
                            return false;
                        }
                    });
                    if(autoSearchSelector.data( "ui-autocomplete" )){
                        autoSearchSelector.data( "ui-autocomplete" )._renderItem = function(ul,item){
                            var html = item.html;
                            var li_element = $("<li></li>").data("ui-autocomplete-item",item).append(html).appendTo(ul);
                            return li_element;
                        }

                    } else {
                        autoSearchSelector.data( "uiAutocomplete" )._renderItem = function(ul,item){
                            var html = item.html;
                            var li_element = $("<li></li>").data("ui-autocomplete-item",item).append(html).appendTo(ul);
                            return li_element;
                        }
                    }
                    autoSearchSelector.on("click change", function(){
                        var autoSearchText = $.trim(autoSearchSelector.val());
                        if(autoSearchText){
                            var iUi = autoSearchBlock.find('.ui-autocomplete').eq(0);
                            if(typeof(cache[autoSearchText]) !== 'undefined'){
                                if(iUi.html()){
                                    iUi.css({'display':'block'});
                                }
                            }
                        }
                    });
                } else {
                    console.log('autocomplete');
                }
            });
        });
    });
</script>